[package]
name = "flappy_game"         # Name of the crate (used when importing or publishing)
version = "0.1.0"            # Semantic versioning
edition = "2024"             # Rust edition (2021 is current and recommended)

[dependencies]
bracket-lib = "~0.8.7"
